### ISSUE TITLE
📂 File Input Component 🗃

### ISSUE THREAD

**Issue by lolottetheclash** [okp4/ui#300]
### **Purpose**

The `FileInput` component allows the user to select one or more files by dragging and dropping them, or by using the file explorer from its computer.

#### Dark Theme

<img width="444" alt="Capture d’écran 2022-06-21 à 17 49 41" src="https://user-images.githubusercontent.com/35332974/174843217-08fa071b-ace7-4f05-b10c-0de2078ecaa9.png">

#### Light Theme

<img width="460" alt="Capture d’écran 2022-06-21 à 17 49 47" src="https://user-images.githubusercontent.com/35332974/174843202-0f44d740-2435-4f3d-8bc9-fddc91d47d4f.png">

### **Use cases**

The user will be able to use this component as soon as he wants to download one or several files of his choice.

#### **Typology**

`FileInput` is an atom component.

#### **Properties**

`label: string` : the main title, here "Drop your files here"
`isMultiple?:boolean`: upload one or multiple files.Default true 
`description?: string`: an optional property which display some context information to the user (here: "Supports: CSV, XLS, XLXS, ..."
`acceptedFormats?: string[]`: optional list of accepted formats.Default all are accepted. 
`onDropped: (files: Files) => void`: a callback to handle dropped files
`maxFilesSize?: number`: the max size authorized for uploaded files
`size?: "large" | "medium"| "small"`

#### **State**

NA

### **Notes**

NA

**Comment by lolottetheclash** [comment]
@ccamel @fredericvilcot @ErikssonJoakim @JoeyDjr Here is the first version of the `DragAndDrop` component to implement. 
There are certainly additions/modifications to bring, do not hesitate!

**Comment by lolottetheclash** [comment]
@ccamel You're right, the name is too specific since it offers two file upload methods.
`FileUpload` sounds good to me, but maybe it's better to put it in plural since it will be able to handle multiple file downloads (like `FilesUpload`)?
We talked about the possible upload of folders this morning and we didn't retain this possibility for the moment. 
Maybe we should add this possibility anyway?
Concerning the `description` we also considered passing it a JSX element but we wanted to keep it as simple as possible for the 1st version.
It seemed to me that it could be useful to offer the possibility to the user to limit the size of the uploaded files and to send a warning message if the uploaded file is too big.
Indeed, the component is as stupid as possible and must let the management of displays by its parent.
What do you think about all this @fredericvilcot ?

**Comment by fredericvilcot** [comment]
@ccamel @lolottetheclash @JoeyDjr 

- obviously, we haven't really discussed the name of the component but I'm leaning towards `FileUpload` in the singular because the notion of multiple uploads is optional.
- if you don't mind, I would prefer to implement folder(s) upload in a next version to ensure rapid delivery of components in their minimum version in order to make our applications quickly functional.
- I'm OK to implement the `description` property as a `JSX Element` because I don't think it's much more complex to do it.
- good catch for the `maxFilesSize` property, I suggest to remove it for now, this can be discussed later depending on new user needs.
- you raise an important question concerning the notion of displaying the progress / selections of file uploads that we have to rule for this version of the component. To tie these notions to display, I see two main ways to do it: 
👉 As progress / loading / selection notions are directly part of the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) API we will use for uploading files, we could consider adding a local state that can hold those informations in the same component and, by the way, embeds an additional section that can render the selected files with their upload progress bar.
👉 If we still want to keep the FileUpload component as dumb as possible, we must add callback methods through props that can handle file selection,  start / end of progress ... Those callback must be implemented by the parent and should call a dedicated `useCase` upon hexagonal architecture.
IMHO, the first way is easier as everything is handled into the component. Moreover, I think we should avoid adding UI logic into hexagonal architecture that must only hold business logic. What do you think @ccamel ?

**Comment by ccamel** [comment]
@fredericvilcot Sorry for this "burst" of lucidity but I would like to redefine the responsibility outline of this component. From my point of view, for now, the component is not a  "FileUpload" component, since it does not upload the files, but just collects the file to be uploaded (or processed in any other ways), while controlling consistency (maximum number of files, file sizes, etc.). In other words, the upload action (or any other action on the files) is performed outside the component. The component then acts as a "File Drop Zone". Note that the idea I want to promote here is the re-usability. Indeed, this component could be reused to manage avatars or logos for data spaces or data sets.

OK, so, from this point of view, the question that remains is, dumb or not dumb? Well, if the component manages a state (list of files), applies business rules for the coherence of this state, well, from a hexagonal point of view, we should create a domain and use cases. 

Of course, I understand your point of view to deliver quickly, but if during the development we can make the component more generic and reusable in a maximum of other contexts: we win! I suggest that we discuss this together in person if you prefer.

**Comment by JoeyDjr** [comment]
As we discuss with @ccamel and @fredericvilcot, the component is a dumb component. So it only allows collect files and send them via the callback method 'onDropped' (`onDropped: (files: FileList | null) => void`). We rename the component 'FileInput' because it is only an input for files.

**Comment by JoeyDjr** [comment]
Hello @ccamel @lolottetheclash @fredericvilcot @ErikssonJoakim 
Concerning the `id` prop of the component. It seems is not a good idea to provide it (mandatory even more). 
There is two solutions to remove it : 

1.  Manage random id into the component
And keep all like it is now
2.  Manage a state local for the component and declare it molecule instead of atom
And use this local state conditionally apply dragging and error classes
3.  Another solution

Let's vote for the better solution

**Comment by ccamel** [comment]
@JoeyDjr  I don't think there is a need for id here. Please clarify.
